kind: ServiceAccount
apiVersion: v1
metadata:
  name: prow-pipeline
  namespace: prow

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-pipeline
  namespace: prow
rules:
- apiGroups:
  - tekton.dev  #pipeline.tekton.dev
  resources:
  - pipelineresources
  - pipelineruns
  - pipelines
  - tasks
  - taskruns
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - update
- apiGroups:
  - prow.k8s.io
  resources:
  - prowjobs
  - prowjobs/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-pipeline
  namespace: prow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prow-pipeline
subjects:
- kind: ServiceAccount
  name: prow-pipeline
 # namespace: default #prow
  namespace: prow
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: prow-pipeline
  namespace: prow
  labels:
    app: prow-pipeline
  annotations:
    wave.pusher.com/update-on-config-change: "true"
spec:
  replicas: 1      #Do not scale up
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prow-pipeline
  template:
    metadata:
      labels:
        app: prow-pipeline
    spec:
      serviceAccount: prow-pipeline
      containers:
      - name: pipeline
        image: gcr.io/k8s-prow/pipeline:latest  #gcr.io/k8s-testimages/pipeline:latest  # Note: not gcr.io/k8s-prow for dev
        imagePullPolicy: Always  # Good practice for dev/debugging, bad for prod
        args:
        - --config=/etc/config/config.yaml #/root/test-infra/config/prow/config.yaml 
        volumeMounts:
        - mountPath: /etc/config     #/root/test-infra/config/prow            
          name: config
          readOnly: true
      volumes:
      - name: config
        configMap:
          # This should be the name of the config map for your prow instance
          name: config

